### ISSUE TITLE
How to install EMGD-Community on Debian

### ISSUE THREAD

**Issue by mbradley612** [EMGD-Community/intel-binaries-linux#33]
Hi Thomas,

Many thanks for all of your work on this project, it is exactly what we need to provide EMGD support for our project.

Our preferred target platform is a recent Debian build - we need a 3.6 kernel for the touch screen we are using. I can see you have a Debian folder, so I'm assuming you support Debian but it's not obvious to me how we install the binaries into Debian. Can you give us any clues?

Very many thanks,

Matthew

**Comment by thopiekar** [comment]
Hi Matthew,

sorry for answering you so late, but I was busy because of my studies.
The reason for the "debian" folder is, that it contains all packaging file for debian-based distributions, in our case Ubuntu, which I'm focusing on because I use this PPA, as you might know.

https://launchpad.net/~thopiekar/+archive/ubuntu/emgd

Well, you can try to add the PPA into your apt's sources.list, but I don't beleave that it will work (at least not on wheezy) to install any package because all builds are made against libc6 whose version is higher on Ubuntu as on Debian.
So a solution would be to rebuild all package for your Debian version. I can just prefer to keep focusing on wheezy if you will need video-playback acceleration, because on Debian wheezy libva is at version 1.0.16, which is exact the version you'll need for EMGD.
So all applications which are using libva on Debian will work of course!

I think you can feel also lucky that you need kernel 3.6 already. I think you will be able to build EMGD's drm kernel module with it. I remember I didn't made many patches compatible for 3.2, which is default on wheezy.
Don't know whether dkms finds custom kernel builds, but in case it doesn't browse the web for debian packages containing kernel 3.6 (or maybe higher version depending on your touchscreen). They often work well with dkms and trigger a build on kernel installation, when EMGD ("emgd-driver-drm-dkms" package I think) was already built.

Hope it was more support than you ever could get by Intel ;)

Regards

**Comment by mbradley612** [comment]
Hi Thomas,

Many thanks for this, we really appreciate it. Based on your advice, we're currently using Xbuntu and are making good progress - we'll contribute back how we get on our target device, an fit-PC2i
http://www.fit-pc.com/wiki/index.php/Fit-PC_Product_Line:_fit-PC2/2i

Matthew

**Comment by thopiekar** [comment]
How are your experiences?

**Comment by mbradley612** [comment]
Hi Thomas,

We discovered that the latest Ubuntu distro (14.04 and later) include EMGD out of the box. Perhaps they are your binaries? 

So to keep our install as simple as possible, this is what we will be using. Thanks again for all your help,

Matthew

**Comment by thopiekar** [comment]
No, this is the opensource driver, which only has 2D acceleration. So, in case you plan to develop OpenGL applications. Additionally it also does not have hardware video decoding ( see libva ).
But depending on your needs the opensource driver can be enough.
